version: '3'
services:
 web:
  image: rabbitmq:3-management
  container_name: rabbit_web
  ports:
   - "15672:15672"
  links:
   - rabbit-reader
 
 rabbit-reader:
  image: rabbit
  container_name: rabbit_reader
  build: .
